CREATE TABLE DEPARTMENT (	
    "ID"                    INTEGER NOT NULL,
    "NAME"                  VARCHAR2(25) NOT NULL,
     PHONE                  INTEGER NOT NULL,
     FAX_NUMBER             INTEGER, 
     "LOCATION"             VARCHAR2(30),
     
     CONSTRAINT             DEPARTMENT_ID_PK PRIMARY KEY ("ID")
);

CREATE TYPE PERSON_TYPE AS OBJECT (	
    "ID"                    INTEGER, 
    FIRST_NAME              VARCHAR2(25),
    LAST_NAME               VARCHAR2(25),
    PHONE                   INTEGER,
    DATE_OF_BIRTH           DATE,
    STREET                  VARCHAR2(50), 
    POST_CODE               INTEGER,
    TOWN                    VARCHAR2(50),
    GENDER                  VARCHAR2(1)
) NOT FINAL;
/

CREATE TABLE PERSON OF PERSON_TYPE (
    CONSTRAINT PERSON_ID_PK PRIMARY KEY ("ID"),
    CONSTRAINT PERSON_GENDER_CHECK CHECK (GENDER IN ('F', 'M'))
);

CREATE TYPE STAFF_TYPE UNDER PERSON_TYPE (
   DEPARTMENT_ID            INTEGER,
   SALARY                   NUMBER(8,2),
   "ROLE"                   VARCHAR2(50),
   EXTENSION                INTEGER,
   OFFICE_NUMBER            INTEGER,
   POSITION                 VARCHAR2(30)
) NOT FINAL;
/

CREATE TABLE STAFF OF STAFF_TYPE (
    CONSTRAINT STAFF_ID_PK PRIMARY KEY ("ID"),
    CONSTRAINT STAFF_DEPARTMENT_ID_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT
);

CREATE TYPE STUDENT_TYPE UNDER PERSON_TYPE (
   COURSE_ID               INTEGER,
   HAS_LOAN                CHAR(1)
);
/

CREATE  TABLE STUDENT OF STUDENT_TYPE (
    CONSTRAINT STUDENT_ID_PK PRIMARY KEY ("ID")    
);

CREATE TYPE NEXT_OF_KIN_TYPE UNDER PERSON_TYPE (
   STUDENT_ID               INTEGER,
   RELATIONSHIP             VARCHAR2(30)
);
/

CREATE TABLE NEXT_OF_KIN OF NEXT_OF_KIN_TYPE (
    CONSTRAINT NEXT_OF_KIN_ID_PK PRIMARY KEY ("ID")    
);

CREATE TYPE HEAD_OF_DEPARTMENT_TYPE UNDER STAFF_TYPE (
   START_DATE               DATE,
   END_DATE                 DATE
);
/

CREATE TABLE HEAD_OF_DEPARTMENT OF HEAD_OF_DEPARTMENT_TYPE (
    CONSTRAINT HEAD_OF_DEPARTMENT_ID_PK PRIMARY KEY ("ID")
);

CREATE TABLE COURSE (	
    "ID"                    INTEGER NOT NULL,
    "NAME"                  VARCHAR2(50) NOT NULL,
    "DURATION"              INTEGER NOT NULL,
     DEPARTMENT_ID          INTEGER NOT NULL, 
     COORDINATOR_ID         INTEGER NOT NULL, 
     
-- THE CONSTRAINT NAME INCLUDES THE NAME OF THIS PARTICULAR TABLE AS IT BELONGS TO IT; 
     CONSTRAINT COURSE_ID_PK PRIMARY KEY ("ID"),
     CONSTRAINT COURSE_DEPARTMENT_ID_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT,
     CONSTRAINT COURSE_COORDINATOR_ID_FK FOREIGN KEY (COORDINATOR_ID) REFERENCES STAFF
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_COURSE_ID_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE;

CREATE TABLE PAPER (	
    "ID"                    INTEGER NOT NULL,
    TITLE                  VARCHAR2(25) NOT NULL,
    START_DATE             DATE NOT NULL,
    END_DATE               DATE NOT NULL,
    MIN_GRADE_TO_PASS      INTEGER NOT NULL,
    COORDINATOR_ID         INTEGER NOT NULL, 
     
     CONSTRAINT PAPER_ID_PK PRIMARY KEY ("ID"),
     CONSTRAINT PAPER_COORDINATOR_ID_FK FOREIGN KEY (COORDINATOR_ID) REFERENCES STAFF
);

CREATE TABLE COURSE_PAPER( 
    COURSE_ID             INTEGER NOT NULL, 
    PAPER_ID              INTEGER NOT NULL, 

    --PATTERN COULD NOT BE FOLLOWED ON THE FIRST CONSTRAINT AS THE NAME WAS TOO LONG 
     CONSTRAINT COURSE_ID_PAPER_ID_PK PRIMARY KEY (COURSE_ID, PAPER_ID), 
     CONSTRAINT COURSE_ID_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE,
     CONSTRAINT COURSE_PAPER_PAPER_ID_FK FOREIGN KEY (PAPER_ID) REFERENCES PAPER
);

CREATE TABLE TEACHING (
     PAPER_ID              INTEGER NOT NULL, 
     STAFF_ID              INTEGER NOT NULL, 
     HOURS_PER_WEEK        INTEGER NOT NULL,
     
     CONSTRAINT TEACHING_STAFF_ID_PAPER_ID_PK PRIMARY KEY (STAFF_ID, PAPER_ID), 
     CONSTRAINT TEACHING_PAPER_ID_FK FOREIGN KEY (PAPER_ID) REFERENCES PAPER,
     CONSTRAINT TEACHING_STAFF_ID_FK FOREIGN KEY (STAFF_ID) REFERENCES STAFF
);

CREATE TABLE "RESOURCE" (
      "ID"              INTEGER NOT NULL, 
      "NAME"            VARCHAR2(50) NOT NULL,
      "DESCRIPTION"       VARCHAR2(2000)
      
--     Non sense ORA-00907 error ???  
--     CONSTRAINT COURSE_ID_PK PRIMARY KEY ("ID")
);

ALTER TABLE "RESOURCE" ADD CONSTRAINT RESOURCE_ID_PK PRIMARY KEY ("ID");

CREATE TABLE RESOURCE_PAPER( 
    RESOURCE_ID           INTEGER NOT NULL, 
    PAPER_ID              INTEGER NOT NULL, 
    -- TABLE NAME NOT INCLUDED IN CONSTRAINT NAME AS: SQL Error: ORA-00972: identifier is too long
     CONSTRAINT RESOURCE_ID_PAPER_ID_PK PRIMARY KEY (RESOURCE_ID, PAPER_ID), 
     CONSTRAINT RESOURCE_PAPER_RESOURCE_ID_FK FOREIGN KEY (RESOURCE_ID) REFERENCES "RESOURCE",
     CONSTRAINT RESOURCE_PAPER_PAPER_ID_FK FOREIGN KEY (PAPER_ID) REFERENCES PAPER
);

CREATE TABLE PAPER_STUDENT( 
    STUDENT_ID            INTEGER NOT NULL, 
    PAPER_ID              INTEGER NOT NULL, 
    "PERFORMANCE"         INTEGER,
    -- TABLE NAME NOT INCLUDED IN CONSTRAINT NAME AS: SQL Error: ORA-00972: identifier is too long
     CONSTRAINT STUDENT_ID_PAPER_ID_PK PRIMARY KEY (STUDENT_ID, PAPER_ID), 
     CONSTRAINT PAPER_STUDENT_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT,
     CONSTRAINT PAPER_STUDENT_PAPER_ID_FK FOREIGN KEY (PAPER_ID) REFERENCES PAPER
);

CREATE TABLE ASSESSMENT(
   "ID"                 INTEGER NOT NULL,
   "NAME"               VARCHAR2(30)NOT NULL,
   WEIGHT               DECIMAL(8,2) NOT NULL,
   PAPER_ID             INTEGER NOT NULL,
   
   CONSTRAINT ASSESSMENT_ID_PK PRIMARY KEY ("ID"), 
   CONSTRAINT ASSESSMENT_PAPER_ID_FK FOREIGN KEY (PAPER_ID) REFERENCES PAPER
);

CREATE TABLE GRADE( 
    "ID"              INTEGER NOT NULL, 
    GRADE             INTEGER NOT NULL, 
    ASSESSMENT_ID     INTEGER NOT NULL, 
    STUDENT_ID        INTEGER NOT NULL,

     CONSTRAINT GRADE_ID_PK PRIMARY KEY ("ID"), 
     CONSTRAINT GRADE_ASSESSMENT_ID_FK FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT,
     CONSTRAINT GRADE_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT
);

CREATE TABLE QUALIFICATION(
   "ID"             INTEGER NOT NULL, 
   "NAME"           VARCHAR2(100) NOT NULL, 

    CONSTRAINT QUALIFICATION_ID_PK PRIMARY KEY ("ID")
);

CREATE TABLE STAFF_QUALIFICATION(
   STAFF_ID             INTEGER NOT NULL, 
   QUALIFICATION_ID     INTEGER NOT NULL, 

    -- TABLE NAME NOT INCLUDED IN CONSTRAINT NAMES AS: SQL Error: ORA-00972: identifier is too long
    CONSTRAINT STAFF_ID_QUALIFICATION_ID_PK PRIMARY KEY (STAFF_ID, QUALIFICATION_ID),
    CONSTRAINT STAFF_Q_STAFF_ID_FK FOREIGN KEY (STAFF_ID) REFERENCES STAFF,
    CONSTRAINT STAFF_Q_QUALIFICATION_ID_FK FOREIGN KEY (QUALIFICATION_ID) REFERENCES QUALIFICATION
);